schema_version = "1.0.0"

id = "f64render"
version = "1.0.0"
name = "f64render"
tagline = "Render engine for fast64 materials"
maintainer = "Max Bebök, Fast64 community"
type = "add-on"

website = "https://github.com/Fast-64/f64render"

tags = ["3D View", "Material", "Render"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
